//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_comparacao
    {
        public int id_comparacao { get; set; }
        public System.DateTime com_data_hora { get; set; }
        public string com_nfe_id { get; set; }
        public Nullable<int> com_item_id { get; set; }
        public string com_campo { get; set; }
        public string com_valor_df { get; set; }
        public string com_valor_sap { get; set; }
        public string com_usuario { get; set; }
        public string PEDCOM { get; set; }
        public Nullable<int> ITEPED { get; set; }
    }
}
