//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.GroupUsers = new HashSet<GroupUsers>();
            this.MotivoCorrecao = new HashSet<MotivoCorrecao>();
        }
    
        public int IdGroup { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<GroupUsers> GroupUsers { get; set; }
        public virtual ICollection<MotivoCorrecao> MotivoCorrecao { get; set; }
    }
}
