//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUsers
    {
        public int IdGroupUser { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public string LoginName { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
