//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoCorrecao
    {
        public MotivoCorrecao()
        {
            this.Ocorrencias = new HashSet<Ocorrencias>();
        }
    
        public int IdMotivoCorrecao { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string TipoDocumento { get; set; }
        public string Classificacao { get; set; }
        public string Responsavel { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<bool> InformaResponsavel { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<Ocorrencias> Ocorrencias { get; set; }
    }
}
