//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocorrencias
    {
        public Ocorrencias()
        {
            this.OcorrenciasComentarios = new HashSet<OcorrenciasComentarios>();
        }
    
        public int IdOcorrencia { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public Nullable<System.DateTime> DataEsperada { get; set; }
        public string Responsavel { get; set; }
        public string Status { get; set; }
        public string NFEID { get; set; }
        public Nullable<int> IdMotivoCorrecao { get; set; }
    
        public virtual MotivoCorrecao MotivoCorrecao { get; set; }
        public virtual ICollection<OcorrenciasComentarios> OcorrenciasComentarios { get; set; }
    }
}
