//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Groups> Groups { get; set; }
        public DbSet<GroupUsers> GroupUsers { get; set; }
        public DbSet<MotivoCorrecao> MotivoCorrecao { get; set; }
        public DbSet<Ocorrencias> Ocorrencias { get; set; }
        public DbSet<OcorrenciasComentarios> OcorrenciasComentarios { get; set; }
        public DbSet<TbCOM> TbCOM { get; set; }
        public DbSet<TbCON> TbCON { get; set; }
        public DbSet<TbNFE> TbNFE { get; set; }
        public DbSet<Status_NotaFiscal> Status_NotaFiscal { get; set; }
        public DbSet<Talonario> Talonario { get; set; }
        public DbSet<TalonarioItem> TalonarioItem { get; set; }
        public DbSet<TbDOC_CAB> TbDOC_CAB { get; set; }
        public DbSet<TbFOR> TbFOR { get; set; }
        public DbSet<TbStatusMateriaisBloqueados> TbStatusMateriaisBloqueados { get; set; }
        public DbSet<TbValidacoes> TbValidacoes { get; set; }
        public DbSet<TbVER> TbVER { get; set; }
        public DbSet<ToleranciaValidacao> ToleranciaValidacao { get; set; }
        public DbSet<TbLOGApplication> TbLOGApplication { get; set; }
        public DbSet<Classificacao> Classificacao { get; set; }
        public DbSet<com_comparacao> com_comparacao { get; set; }
        public DbSet<TbCFOP> TbCFOP { get; set; }
        public DbSet<TbDOC_ITEM> TbDOC_ITEM { get; set; }
        public DbSet<TbModoProcessoCategoriaContabil> TbModoProcessoCategoriaContabil { get; set; }
        public DbSet<TbModoProcessoCfop> TbModoProcessoCfop { get; set; }
        public DbSet<TbDOC_CAB_NFE_REF> TbDOC_CAB_NFE_REF { get; set; }
        public DbSet<TbPlantaCnpj> TbPlantaCnpj { get; set; }
        public DbSet<TbJUN> TbJUN { get; set; }
        public DbSet<TbLOG> TbLOG { get; set; }
        public DbSet<TbUsuario> TbUsuario { get; set; }
        public DbSet<TbDOC_CAB_ANEXOS> TbDOC_CAB_ANEXOS { get; set; }
        public DbSet<TbDOC_CAB_CTE> TbDOC_CAB_CTE { get; set; }
        public DbSet<TbDOC_CAB_SAP> TbDOC_CAB_SAP { get; set; }
        public DbSet<TbDOC_ITEM_CTE> TbDOC_ITEM_CTE { get; set; }
        public DbSet<TbDOC_ITEM_NFE> TbDOC_ITEM_NFE { get; set; }
        public DbSet<TbAcesso> TbAcesso { get; set; }
        public DbSet<vwTALONARIO> vwTALONARIO { get; set; }
        public DbSet<tbImportacaoNotaFiscal> tbImportacaoNotaFiscal { get; set; }
        public DbSet<vwIntegracaoPSGetPdf> vwIntegracaoPSGetPdf { get; set; }
        public DbSet<TbModoProcessoDetalhe> TbModoProcessoDetalhe { get; set; }
        public DbSet<TBJ1B1N_CFOP_PARCEIRO> TBJ1B1N_CFOP_PARCEIRO { get; set; }
        public DbSet<TBJ1B1N_PLANTA_METSO_PARCEIRO> TBJ1B1N_PLANTA_METSO_PARCEIRO { get; set; }
        public DbSet<TBJ1B1N_DE_PARA_CFOP_ESCRITURAR> TBJ1B1N_DE_PARA_CFOP_ESCRITURAR { get; set; }
        public DbSet<VWJ1B1N_IMPOSTO_POR_CFOP_COFINS> VWJ1B1N_IMPOSTO_POR_CFOP_COFINS { get; set; }
        public DbSet<VWJ1B1N_IMPOSTO_POR_CFOP_IPI> VWJ1B1N_IMPOSTO_POR_CFOP_IPI { get; set; }
        public DbSet<VWJ1B1N_IMPOSTO_POR_CFOP_PIS> VWJ1B1N_IMPOSTO_POR_CFOP_PIS { get; set; }
        public DbSet<VWJ1B1N_DE_PARA_MATERIAL> VWJ1B1N_DE_PARA_MATERIAL { get; set; }
        public DbSet<TBJ1B1N_DIREITO_FISCAL> TBJ1B1N_DIREITO_FISCAL { get; set; }
        public DbSet<VWJ1B1N_DIREITO_FISCAL_ICMS> VWJ1B1N_DIREITO_FISCAL_ICMS { get; set; }
        public DbSet<VWJ1B1N_DIREITO_FISCAL_IPI> VWJ1B1N_DIREITO_FISCAL_IPI { get; set; }
        public DbSet<VWJ1B1N_DIREITO_FISCAL_PIS> VWJ1B1N_DIREITO_FISCAL_PIS { get; set; }
        public DbSet<TBDOC_CONSIGNACAO_REFNF> TBDOC_CONSIGNACAO_REFNF { get; set; }
        public DbSet<TbDOC_CAB_NFE> TbDOC_CAB_NFE { get; set; }
        public DbSet<TBJ1B1N_TIPO_IMPOSTO_POR_CFOP> TBJ1B1N_TIPO_IMPOSTO_POR_CFOP { get; set; }
        public DbSet<VWJ1B1N_IMPOSTO_POR_CFOP_ICMS> VWJ1B1N_IMPOSTO_POR_CFOP_ICMS { get; set; }
        public DbSet<TBJ1B1N_DADOS_METSO_PADRAO> TBJ1B1N_DADOS_METSO_PADRAO { get; set; }
        public DbSet<VWJ1B1N_DIREITO_FISCAL_COFINS> VWJ1B1N_DIREITO_FISCAL_COFINS { get; set; }
        public DbSet<TbValidacoesExcecoes> TbValidacoesExcecoes { get; set; }
        public DbSet<TBJ1B1N_CAB_NFE> TBJ1B1N_CAB_NFE { get; set; }
        public DbSet<TBJ1B1N_ITEM_NFE> TBJ1B1N_ITEM_NFE { get; set; }
        public DbSet<TBJ1B1N_ITEMTAX_NFE> TBJ1B1N_ITEMTAX_NFE { get; set; }
        public DbSet<TBJ1B1N_COD_MATERIAL_DESCRICAO> TBJ1B1N_COD_MATERIAL_DESCRICAO { get; set; }
        public DbSet<TBDOC_SUBCONTRATACAO_REFNF> TBDOC_SUBCONTRATACAO_REFNF { get; set; }
        public DbSet<TBDOC_NOTA_COMPLEMENTAR_REFNF> TBDOC_NOTA_COMPLEMENTAR_REFNF { get; set; }
        public DbSet<TbModoProcesso> TbModoProcesso { get; set; }
        public DbSet<TBJ1B1N_CADASTRO_CFOP> TBJ1B1N_CADASTRO_CFOP { get; set; }
    
        public virtual int SP_DELETE_TALONARIO(Nullable<int> iDTALONARIO)
        {
            var iDTALONARIOParameter = iDTALONARIO.HasValue ?
                new ObjectParameter("IDTALONARIO", iDTALONARIO) :
                new ObjectParameter("IDTALONARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TALONARIO", iDTALONARIOParameter);
        }
    
        public virtual int SP_ESTORNO_INTEGRACAO_VNF(string nFEID)
        {
            var nFEIDParameter = nFEID != null ?
                new ObjectParameter("NFEID", nFEID) :
                new ObjectParameter("NFEID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ESTORNO_INTEGRACAO_VNF", nFEIDParameter);
        }
    }
}
