//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalonarioItem
    {
        public int IdTalonarioItem { get; set; }
        public Nullable<int> IdTalonario { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Pedido { get; set; }
        public string ItemPedido { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public string NCM { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public string CFOP { get; set; }
        public Nullable<decimal> ICMS { get; set; }
        public Nullable<decimal> IPI { get; set; }
        public Nullable<decimal> FRETE { get; set; }
        public Nullable<decimal> SEGURO { get; set; }
        public Nullable<decimal> DESCONTO { get; set; }
        public Nullable<decimal> OUTRASDESPESAS { get; set; }
        public Nullable<decimal> ICMSAliq { get; set; }
    
        public virtual Talonario Talonario { get; set; }
    }
}
