//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talonario
    {
        public Talonario()
        {
            this.TalonarioItem = new HashSet<TalonarioItem>();
        }
    
        public int IdTalonario { get; set; }
        public string NumeroDocumento { get; set; }
        public string Serie { get; set; }
        public string ChaveAcesso { get; set; }
        public string CNPJEmitente { get; set; }
        public string RazaoSocialEmitente { get; set; }
        public string CNPJMetso { get; set; }
        public string RazaoSocialMetso { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public string Classificacao { get; set; }
        public string Tipo { get; set; }
        public string CodigoVerificacao { get; set; }
        public string LinkDocumento { get; set; }
        public string LinkAplicacao { get; set; }
        public byte[] Anexo { get; set; }
        public string AnexoNome { get; set; }
        public string AnexoExtensao { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public string Responsavel { get; set; }
        public string DataChegada { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Observacao { get; set; }
        public string TipoDocumento { get; set; }
        public string IE_Emitente { get; set; }
        public string IE_Metso { get; set; }
    
        public virtual Status_NotaFiscal Status_NotaFiscal { get; set; }
        public virtual ICollection<TalonarioItem> TalonarioItem { get; set; }
    }
}
