//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAcesso
    {
        public string acecodtel { get; set; }
        public string acecodusu { get; set; }
        public Nullable<System.DateTime> acedatace { get; set; }
        public string acesitace { get; set; }
    }
}
