//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCFOP
    {
        public TbCFOP()
        {
            this.TbModoProcessoCfop = new HashSet<TbModoProcessoCfop>();
        }
    
        public string cfop_codigo { get; set; }
        public string cfop_descricao { get; set; }
        public string cfop_classificacao { get; set; }
    
        public virtual ICollection<TbModoProcessoCfop> TbModoProcessoCfop { get; set; }
    }
}
