//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCOM
    {
        public string CODCOM { get; set; }
        public string NOMCOM { get; set; }
        public string EMAIL { get; set; }
        public string TELCOM { get; set; }
        public Nullable<decimal> CATEGORIA { get; set; }
        public string CATEGORIA_DESC { get; set; }
    }
}
