//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_CAB_CTE
    {
        public string NFEID { get; set; }
        public string CT_IDE_CMUNINI { get; set; }
        public string CT_IDE_XMUNINI { get; set; }
        public string CT_IDE_UFINI { get; set; }
        public string CT_IDE_CMUNFIM { get; set; }
        public string CT_IDE_XMUNFIM { get; set; }
        public string CT_IDE_UFFIM { get; set; }
        public string CT_IDE_RETIRA { get; set; }
        public string CT_IDE_TOMA { get; set; }
        public string CT_TOMA_CNPJ { get; set; }
        public string CT_TOMA_IE { get; set; }
        public string CT_TOMA_XNOME { get; set; }
        public string CT_TOMA_XLGR { get; set; }
        public string CT_TOMA_NRO { get; set; }
        public string CT_TOMA_XBAIRRO { get; set; }
        public string CT_TOMA_CMUN { get; set; }
        public string CT_TOMA_XMUN { get; set; }
        public string CT_TOMA_CEP { get; set; }
        public string CT_TOMA_UF { get; set; }
        public string CT_TOMA_CPAIS { get; set; }
        public string CT_TOMA_XPAIS { get; set; }
        public Nullable<decimal> CT_VPREST_VTPREST { get; set; }
        public Nullable<decimal> CT_VPREST_VREC { get; set; }
        public Nullable<decimal> CT_INFCARGA_VCARGA { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_FRETE_PESO { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_FRETE_VALOR { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_FRETE { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_SEC_CAT { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_ADEME { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_PEDAGIO { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_GRIS { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_TAXAEMICTRC { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_COLETAENTREGA { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_OUTROSVALORES { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_DESCONTO { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_DESPACHO { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_ENTREGA { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_OUTROS { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_ESCOLTA { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_COLETA { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_SEGURO { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_PERNOITE { get; set; }
        public Nullable<decimal> CT_VPREST_COMP_REDESPACHO { get; set; }
        public Nullable<int> CT_IDE_TPCTE { get; set; }
    }
}
