//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_CAB
    {
        public string NFEID { get; set; }
        public string VNF_TIPO_DOCUMENTO { get; set; }
        public string VNF_CONTEUDO_XML { get; set; }
        public string VNF_DANFE_ONLINE { get; set; }
        public System.DateTime VNF_DATA_INSERT { get; set; }
        public string VNF_USUARIO_INSERT { get; set; }
        public byte[] VNF_ANEXO { get; set; }
        public string VNF_ANEXO_NOME { get; set; }
        public string VNF_ANEXO_EXTENSAO { get; set; }
        public string VNF_CODIGO_VERIFICACAO { get; set; }
        public Nullable<bool> VNF_MATERIAL_RECEBIDO { get; set; }
        public string VNF_CLASSIFICACAO { get; set; }
        public Nullable<bool> VNF_RATEAR { get; set; }
    }
}
