//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_CAB_NFE_REF
    {
        public string NFEID { get; set; }
        public string NF_NFREF_REFNFE { get; set; }
        public string NF_NFREF_REFCTE { get; set; }
    }
}
