//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_CAB_SAP
    {
        public string NFEID { get; set; }
        public string SAP_PO_NUMBER { get; set; }
        public Nullable<System.DateTime> SAP_CREATED_ON { get; set; }
        public string SAP_CREATED_BY { get; set; }
        public string SAP_PAYMENT_TERMS { get; set; }
        public string SAP_PURCHASING_GROUP { get; set; }
        public string SAP_CURRENCY { get; set; }
        public string SAP_VENDOR_CODE { get; set; }
        public string SAP_VENDOR_NAME { get; set; }
        public string SAP_VENDOR_CNPJ { get; set; }
        public string SAP_INCOTERMS1 { get; set; }
        public string SAP_VERSION_COMPLETE { get; set; }
        public string SAP_METSO_CNPJ { get; set; }
        public string SAP_RELEASE_INDIC { get; set; }
    }
}
