//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_CAB_ANEXOS
    {
        public int id { get; set; }
        public string NFEID { get; set; }
        public byte[] ANEXO { get; set; }
        public string NOME { get; set; }
        public string EXTENSAO { get; set; }
    }
}
