//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_ITEM
    {
        public int ID_TBDOC_ITEM { get; set; }
        public string NFEID { get; set; }
        public Nullable<short> VNF_CODJUN { get; set; }
        public string VNF_ITEM_VALIDO { get; set; }
        public Nullable<bool> VNF_CONFIRMADO_PORTAL { get; set; }
        public Nullable<int> VNF_ID_MODO_PROCESSO { get; set; }
        public string VNF_INBOUND_DELIVERY_NUMBER { get; set; }
        public Nullable<int> VNF_INBOUND_DELIVERY_ITEM_NUMBER { get; set; }
    
        public virtual TbJUN TbJUN { get; set; }
        public virtual TbModoProcesso TbModoProcesso { get; set; }
    }
}
