//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDOC_SUBCONTRATACAO_REFNF
    {
        public string NFEID { get; set; }
        public int ITEM_NF { get; set; }
        public decimal NUMERO_REFNF { get; set; }
        public int SERIE_REFNF { get; set; }
        public int ITEM_REFNF { get; set; }
    
        public virtual TbDOC_ITEM_NFE TbDOC_ITEM_NFE { get; set; }
    }
}
