//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDOC_CAB_NFE
    {
        public string NFEID { get; set; }
        public Nullable<int> NF_IDE_CUF { get; set; }
        public Nullable<int> NF_IDE_CNF { get; set; }
        public Nullable<int> NF_IDE_INDPAG { get; set; }
        public string NF_IDE_NATOP { get; set; }
        public Nullable<int> NF_IDE_MOD { get; set; }
        public string NF_IDE_SERIE { get; set; }
        public string NF_IDE_NNF { get; set; }
        public Nullable<System.DateTime> NF_IDE_DHEMI { get; set; }
        public Nullable<int> NF_IDE_TPNF { get; set; }
        public Nullable<int> NF_IDE_IDDEST { get; set; }
        public string NF_IDE_CMUNFG { get; set; }
        public Nullable<int> NF_IDE_TPEMISS { get; set; }
        public Nullable<int> NF_IDE_TPAMB { get; set; }
        public Nullable<int> NF_IDE_FINNFE { get; set; }
        public Nullable<int> NF_IDE_INDFINAL { get; set; }
        public Nullable<int> NF_IDE_INDPRES { get; set; }
        public Nullable<int> NF_IDE_PROCEMI { get; set; }
        public string NF_IDE_DHCONT { get; set; }
        public string NF_IDE_XJUST { get; set; }
        public string NF_IDE_NFREF { get; set; }
        public string NF_IDE_MODAL { get; set; }
        public string NF_EMIT_CNPJ { get; set; }
        public string NF_EMIT_XNOME { get; set; }
        public string NF_EMIT_XLGR { get; set; }
        public string NF_EMIT_NRO { get; set; }
        public string NF_EMIT_XCPL { get; set; }
        public string NF_EMIT_XBAIRRO { get; set; }
        public string NF_EMIT_CMUN { get; set; }
        public string NF_EMIT_UF { get; set; }
        public string NF_EMIT_CEP { get; set; }
        public string NF_EMIT_CPAIS { get; set; }
        public string NF_EMIT_XPAIS { get; set; }
        public string NF_EMIT_FONE { get; set; }
        public string NF_EMIT_IE { get; set; }
        public string NF_EMIT_IEST { get; set; }
        public string NF_EMIT_IM { get; set; }
        public string NF_EMIT_CNAE { get; set; }
        public string NF_EMIT_CRT { get; set; }
        public string NF_REM_XNOME { get; set; }
        public string NF_REM_CNPJ { get; set; }
        public string NF_REM_IE { get; set; }
        public string NF_REM_XLGR { get; set; }
        public string NF_REM_NRO { get; set; }
        public string NF_REM_XCPL { get; set; }
        public string NF_REM_XBAIRRO { get; set; }
        public string NF_REM_CMUN { get; set; }
        public string NF_REM_UF { get; set; }
        public string NF_REM_CEP { get; set; }
        public string NF_REM_CPAIS { get; set; }
        public string NF_REM_XPAIS { get; set; }
        public string NF_DEST_XNOME { get; set; }
        public string NF_DEST_CNPJ { get; set; }
        public string NF_DEST_XLGR { get; set; }
        public string NF_DEST_NRO { get; set; }
        public string NF_DEST_XCPL { get; set; }
        public string NF_DEST_XBAIRRO { get; set; }
        public string NF_DEST_XMUN { get; set; }
        public string NF_DEST_UF { get; set; }
        public string NF_DEST_CEP { get; set; }
        public string NF_DEST_CPAIS { get; set; }
        public string NF_DEST_XPAIS { get; set; }
        public string NF_DEST_FONE { get; set; }
        public string NF_DEST_INDIEDEST { get; set; }
        public string NF_DEST_IE { get; set; }
        public string NF_DEST_ISUF { get; set; }
        public string NF_DEST_IM { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VBC { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VICMS { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VBCST { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VST { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VPROD { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VFRETE { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VSEG { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VDESC { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VII { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VIPI { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VPIS { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VCOFINS { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VOUTRO { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VNF { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VTOTTRIB { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VICMSDESON { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VICMSUFDEST { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VICMSUFREMET { get; set; }
        public Nullable<decimal> NF_ICMSTOT_VFCPUFDEST { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VSERV { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VBC { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VISS { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VPIS { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VCOFINS { get; set; }
        public string NF_ISSQNTOT_DTCOMPET { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VDEDUCAO { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VOUTRO { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VDESCINCOD { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VDESCCOND { get; set; }
        public Nullable<decimal> NF_ISSQNTOT_VISSRET { get; set; }
        public string NF_ISSQNTOT_CREGTRIB { get; set; }
        public Nullable<decimal> NF_RETTRIN_VRETPIS { get; set; }
        public Nullable<decimal> NF_RETTRIN_VRETCOFINS { get; set; }
        public Nullable<decimal> NF_RETTRIN_VRETCSLL { get; set; }
        public Nullable<decimal> NF_RETTRIN_VBCIRRF { get; set; }
        public Nullable<decimal> NF_RETTRIN_VIRRF { get; set; }
        public Nullable<decimal> NF_RETTRIN_VBCRETPREV { get; set; }
        public Nullable<decimal> NF_RETTRIN_VRETPREV { get; set; }
        public Nullable<decimal> NF_RETTRANSP_VSERV { get; set; }
        public Nullable<decimal> NF_RETTRANSP_VBCRET { get; set; }
        public Nullable<decimal> NF_RETTRANSP_PICMSRET { get; set; }
        public Nullable<decimal> NF_RETTRANSP_VICMSRET { get; set; }
        public Nullable<int> NF_RETTRANSP_CFOP { get; set; }
        public string NF_RETTRANSP_CMUNFG { get; set; }
        public string NF_COBR_NFAT { get; set; }
        public Nullable<decimal> NF_COBR_VORIG { get; set; }
        public Nullable<decimal> NF_COBR_VDESC { get; set; }
        public Nullable<decimal> NF_COBR_VLIQ { get; set; }
        public string NF_PAG_TPAG { get; set; }
        public Nullable<decimal> NF_PAG_VPAG { get; set; }
        public string NF_PAG_CNPJ { get; set; }
        public string NF_PAG_TBAND { get; set; }
        public string NF_PAG_CAUT { get; set; }
        public string NF_PAG_TPINTEGRA { get; set; }
        public Nullable<bool> NF_OUTROS_SIGNATURE { get; set; }
        public string NF_OUTROS_INFORMACAO_ADICIONAL { get; set; }
        public string NF_OUTROS_VERSAO { get; set; }
        public string NF_OUTROS_STATUS_CODE { get; set; }
        public string NF_OUTROS_STATUS_DESC { get; set; }
        public string NF_TRANSP_MODFRETE { get; set; }
        public string NF_TRANSP_XNOME { get; set; }
        public string NF_TRANSP_CNPJ { get; set; }
        public string NF_TRANSP_IE { get; set; }
        public string NF_TRANSP_XENDER { get; set; }
        public string NF_TRANSP_XMUN { get; set; }
        public string NF_TRANSP_UF { get; set; }
        public string NF_NFREF_REFNNF { get; set; }
        public string NF_NFREF_REFSerie { get; set; }
        public Nullable<System.DateTime> NF_NFREF_REFDHEMI { get; set; }
        public string NF_DEST_CMUN { get; set; }
    }
}
