//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbFOR
    {
        public string CODFOR { get; set; }
        public string RAZFOR { get; set; }
        public string EMAIL_NFE { get; set; }
        public Nullable<decimal> CNPJ { get; set; }
        public string INTEGRADO { get; set; }
        public string HOMOLOGADO { get; set; }
        public string REGIME_ESPECIAL { get; set; }
    }
}
