//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImportacaoNotaFiscal
    {
        public int IdImportacaoNotaFiscal { get; set; }
        public int IdNotaFiscal { get; set; }
        public string ChaveAcesso { get; set; }
        public int IdImportacaoTipoDocumento { get; set; }
    }
}
