//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBJ1B1N_ITEMTAX_NFE
    {
        public int ID_ITEM_TAX { get; set; }
        public string NFEID { get; set; }
        public int ITEM_NF { get; set; }
        public string IMPOSTO { get; set; }
        public string TIPO_DE { get; set; }
        public string TIPO_PARA { get; set; }
        public string LEI_DE { get; set; }
        public string LEI_PARA { get; set; }
        public Nullable<decimal> BASE_CALC_DE { get; set; }
        public Nullable<decimal> BASE_CALC_PARA { get; set; }
        public Nullable<decimal> ALIQUOTA_DE { get; set; }
        public Nullable<decimal> ALIQUOTA_PARA { get; set; }
        public Nullable<decimal> VALOR_DE { get; set; }
        public Nullable<decimal> VALOR_PARA { get; set; }
        public Nullable<decimal> BASE_EXCL_DE { get; set; }
        public Nullable<decimal> BASE_EXCL_PARA { get; set; }
        public Nullable<decimal> BASE_OUTR_DE { get; set; }
        public Nullable<decimal> BASE_OUTR_PARA { get; set; }
    
        public virtual TBJ1B1N_ITEM_NFE TBJ1B1N_ITEM_NFE { get; set; }
    }
}
