//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBJ1B1N_ITEM_NFE
    {
        public TBJ1B1N_ITEM_NFE()
        {
            this.TBJ1B1N_ITEMTAX_NFE = new HashSet<TBJ1B1N_ITEMTAX_NFE>();
        }
    
        public int ID_ITEM { get; set; }
        public string NFEID { get; set; }
        public string CNPJ_EMITENTE { get; set; }
        public int ITEM_NF { get; set; }
        public string ITEM_TYPE_DE { get; set; }
        public string ITEM_TYPE_PARA { get; set; }
        public string COD_MATERIAL_DE { get; set; }
        public string COD_MATERIAL_PARA { get; set; }
        public string PLANTA_DE { get; set; }
        public string PLANTA_PARA { get; set; }
        public double QUANTIDADE_DE { get; set; }
        public double QUANTIDADE_PARA { get; set; }
        public double VALOR_UNIT_DE { get; set; }
        public double VALOR_UNIT_PARA { get; set; }
        public string UNIDADE_DE { get; set; }
        public string UNIDADE_PARA { get; set; }
        public double VALOR_TOT_DE { get; set; }
        public double VALOR_TOT_PARA { get; set; }
        public string CFOP_DE { get; set; }
        public string CFOP_PARA { get; set; }
        public string NCM_DE { get; set; }
        public string NCM_PARA { get; set; }
        public Nullable<short> MAT_ORIG_DE { get; set; }
        public Nullable<short> MAT_ORIG_PARA { get; set; }
        public string MAT_USO { get; set; }
        public string MAT_GRUPO_MATKL { get; set; }
        public string MAT_DESCRICAO_MAKTX { get; set; }
        public string DOCNUM_REF { get; set; }
        public Nullable<int> ITEM_DOCNUM_REF { get; set; }
        public string SALVO { get; set; }
    
        public virtual TBJ1B1N_CAB_NFE TBJ1B1N_CAB_NFE { get; set; }
        public virtual ICollection<TBJ1B1N_ITEMTAX_NFE> TBJ1B1N_ITEMTAX_NFE { get; set; }
    }
}
