//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBJ1B1N_COD_MATERIAL_DESCRICAO
    {
        public int ID_ITEM { get; set; }
        public string COD_MATERIAL { get; set; }
    }
}
