//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBJ1B1N_CAB_NFE
    {
        public TBJ1B1N_CAB_NFE()
        {
            this.TBJ1B1N_ITEM_NFE = new HashSet<TBJ1B1N_ITEM_NFE>();
        }
    
        public string NFEID { get; set; }
        public string NFTYPE_DE { get; set; }
        public string NFTYPE_PARA { get; set; }
        public string PARTNER_TYPE_DE { get; set; }
        public string PARTNER_TYPE_PARA { get; set; }
        public string PARTNER_FUNCTION_DE { get; set; }
        public string PARTNER_FUNCTION_PARA { get; set; }
        public Nullable<int> PARTNER_ID { get; set; }
        public string OBSERVACAO { get; set; }
        public string DOCNUM_REF { get; set; }
        public string SALVO { get; set; }
        public string DOC_NUM_J1B1N { get; set; }
    
        public virtual ICollection<TBJ1B1N_ITEM_NFE> TBJ1B1N_ITEM_NFE { get; set; }
    }
}
