//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbJUN
    {
        public TbJUN()
        {
            this.TbDOC_ITEM = new HashSet<TbDOC_ITEM>();
        }
    
        public short CODJUN { get; set; }
        public string PEDCOM { get; set; }
        public Nullable<int> ITEPED { get; set; }
        public string NFEID { get; set; }
        public int ITENFE { get; set; }
        public string ITEVAL { get; set; }
        public string CODUSU { get; set; }
        public string CODCOM { get; set; }
        public string MOTIVO { get; set; }
        public string NCMNFE { get; set; }
        public string NCMPED { get; set; }
    
        public virtual ICollection<TbDOC_ITEM> TbDOC_ITEM { get; set; }
    }
}
