//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbLOG
    {
        public int CODLOG { get; set; }
        public Nullable<short> CODJUN { get; set; }
        public string NFEID { get; set; }
        public Nullable<int> ITENFE { get; set; }
        public string CAMPO { get; set; }
        public System.DateTime DATLOG { get; set; }
        public string VALOR_NFE { get; set; }
        public string VALOR_PED { get; set; }
        public string CODCOM { get; set; }
        public string CODFOR { get; set; }
        public string SITUACAO { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<System.DateTime> DATA_CORRECAO { get; set; }
        public string PEDCOM { get; set; }
        public Nullable<int> ITEPED { get; set; }
        public string acecodusu { get; set; }
        public string JUSTIFICATIVA { get; set; }
        public string CODMAT { get; set; }
        public string DESMAT { get; set; }
        public string DETALHE { get; set; }
        public byte[] ANEXO { get; set; }
        public string ANEXONOME { get; set; }
        public string ANEXOEXTENSAO { get; set; }
    }
}
