//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbLOGApplication
    {
        public int id_log { get; set; }
        public string log_type { get; set; }
        public string log_user { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string log_title { get; set; }
        public string log_description { get; set; }
        public string log_link { get; set; }
        public string log_nfeid { get; set; }
        public string log_icon { get; set; }
    }
}
