//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbModoProcesso
    {
        public TbModoProcesso()
        {
            this.TbDOC_ITEM = new HashSet<TbDOC_ITEM>();
            this.TbModoProcessoCategoriaContabil = new HashSet<TbModoProcessoCategoriaContabil>();
            this.TbModoProcessoCfop = new HashSet<TbModoProcessoCfop>();
        }
    
        public int id_modo_processo { get; set; }
        public string mod_tipo_documento { get; set; }
        public string mod_moeda { get; set; }
        public string mod_planta { get; set; }
        public string mod_tipo_material { get; set; }
        public Nullable<int> mod_max_caracteres_num_nf { get; set; }
        public Nullable<int> mod_prioridade { get; set; }
        public Nullable<int> mod_id_modo_processo_detalhe { get; set; }
        public string mod_tipo_frete { get; set; }
        public string mod_item_category { get; set; }
        public string mod_nf_complementar { get; set; }
    
        public virtual ICollection<TbDOC_ITEM> TbDOC_ITEM { get; set; }
        public virtual TbModoProcessoDetalhe TbModoProcessoDetalhe { get; set; }
        public virtual ICollection<TbModoProcessoCategoriaContabil> TbModoProcessoCategoriaContabil { get; set; }
        public virtual ICollection<TbModoProcessoCfop> TbModoProcessoCfop { get; set; }
    }
}
