//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbModoProcessoDetalhe
    {
        public TbModoProcessoDetalhe()
        {
            this.TbModoProcesso = new HashSet<TbModoProcesso>();
        }
    
        public int id_modo_processo_detalhe { get; set; }
        public string mpd_modo { get; set; }
        public string mdp_processo { get; set; }
        public string mdp_tipo_movimento_migo { get; set; }
        public Nullable<bool> mdp_aguardar_liberacao_migo { get; set; }
        public Nullable<bool> mdp_criar_miro { get; set; }
        public string mdp_tipo_miro { get; set; }
        public Nullable<bool> mdp_debito_posterior { get; set; }
        public string mdp_tipo_nf { get; set; }
        public Nullable<bool> mdp_enviar_taxcode_migo { get; set; }
    
        public virtual ICollection<TbModoProcesso> TbModoProcesso { get; set; }
    }
}
