//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbNFE
    {
        public string NFEID { get; set; }
        public string NFEVAL { get; set; }
        public string NFECAN { get; set; }
        public Nullable<decimal> ID_LISTA { get; set; }
        public Nullable<System.DateTime> DATVAL { get; set; }
        public string NFEREL { get; set; }
        public string USUCAN { get; set; }
        public string JUNAUT { get; set; }
        public string SITUACAO { get; set; }
        public string REPROCESSAR { get; set; }
        public string CNPJ_METSO { get; set; }
        public string CONTINGENCIA { get; set; }
        public Nullable<System.DateTime> SAP_DATE_INSERT { get; set; }
        public string SAP_STATUS_INTEGRACAO { get; set; }
        public Nullable<System.DateTime> DTREPROCESSAMENTO { get; set; }
    }
}
