//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbVER
    {
        public string NFEID { get; set; }
        public System.DateTime DATVER { get; set; }
        public string ACAO { get; set; }
        public string SITUACAO { get; set; }
    }
}
