//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToleranciaValidacao
    {
        public int IdToleranciaValidacao { get; set; }
        public Nullable<decimal> ValorDe { get; set; }
        public Nullable<decimal> ValorAte { get; set; }
        public Nullable<decimal> Percentual { get; set; }
    }
}
