//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIntegracaoPSGetPdf
    {
        public int ID { get; set; }
        public string LINK_DOWNLOAD { get; set; }
        public string ANEXO_NF { get; set; }
        public byte[] BINARY_ARQUIVO { get; set; }
    }
}
