//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWJ1B1N_DIREITO_FISCAL_COFINS
    {
        public string TIPO_IMPOSTO { get; set; }
        public string CFOP { get; set; }
        public string UF_DEST { get; set; }
        public string DIREITO_FISCAL_COFINS { get; set; }
        public string VALOR_PADRAO { get; set; }
    }
}
