//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWJ1B1N_DE_PARA_MATERIAL
    {
        public string COD_MATERIAL_DE { get; set; }
        public string COD_MATERIAL_PARA { get; set; }
        public string CNPJ_EMITENTE { get; set; }
        public string MAT_DESCRICAO_MAKTX { get; set; }
        public Nullable<short> MAT_ORIG_PARA { get; set; }
        public string MAT_USO { get; set; }
        public string MAT_GRUPO_MATKL { get; set; }
        public string UNIDADE_PARA { get; set; }
    }
}
