//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNF.Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTALONARIO
    {
        public int IdTalonario { get; set; }
        public string NumeroDocumento { get; set; }
        public string Serie { get; set; }
        public string ChaveAcesso { get; set; }
        public string CNPJEmitente { get; set; }
        public string RazaoSocialEmitente { get; set; }
        public string CNPJMetso { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public string STATUS_INTEGRACAO { get; set; }
        public string IE_Emitente { get; set; }
        public string IE_Metso { get; set; }
    }
}
